In [135]:
import numpy as np

## DataTypes & Attributes

In [136]:
# NumPy's main datatype is ndarray
a1 = np.array([1, 2, 3])
a1

array([1, 2, 3])

In [137]:
a2 = np.array([[1, 2.0, 3.3], [4, 5, 6.5]])
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [138]:
a3 = np.array([
                [[1, 2, 3], [4, 5, 6], [7, 8, 9]], 
                [[10, 11, 12], [13, 14, 15], [16, 17, 18]]
            ])
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [139]:
a1.shape

(3,)

In [140]:
a2.shape

(2, 3)

In [141]:
a3.shape

(2, 3, 3)

In [142]:
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [143]:
a1.dtype, a2.dtype, a3.dtype

(dtype('int64'), dtype('float64'), dtype('int64'))

In [144]:
a1.size, a2.size, a3.size

(3, 6, 18)

In [145]:
type(a1), type(a2), type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [146]:
# create a dataframe from Numpy array
import pandas as pd

df = pd.DataFrame(a2)

df

0    1    2
0  1.0  2.0  3.3
1  4.0  5.0  6.5

In [147]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [148]:
sample_array = np.array([1,2,3])
sample_array

array([1, 2, 3])

In [149]:
sample_array.dtype

dtype('int64')

In [150]:
ones = np.ones((2,3))
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [151]:
ones.dtype

dtype('float64')

In [152]:
type(ones)

numpy.ndarray

In [153]:
zeroes = np.zeros((2,3))
zeroes

array([[0., 0., 0.],
       [0., 0., 0.]])

In [154]:
range_array = np.arange(0,10,2)
range_array

array([0, 2, 4, 6, 8])

In [155]:
type(range_array)

numpy.ndarray

In [156]:
random_array = np.random.randint(0,10, size=(3,5))
random_array

array([[8, 8, 2, 3, 2],
       [0, 8, 8, 3, 8],
       [2, 8, 4, 3, 0]])

In [157]:
np.random.random((5,3))

array([[0.84640867, 0.69947928, 0.29743695],
       [0.81379782, 0.39650574, 0.8811032 ],
       [0.58127287, 0.88173536, 0.69253159],
       [0.72525428, 0.50132438, 0.95608363],
       [0.6439902 , 0.42385505, 0.60639321]])

In [158]:
np.random.seed(seed=0)
random_array_4 = np.random.randint (10, size=(5,3))
random_array_4

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]])

In [159]:
random_array_4.shape

(5, 3)

Viewing arrays and matrices

In [160]:
np.unique(random_array_4)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [161]:
a1

array([1, 2, 3])

In [162]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [163]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [164]:
a1[0]

1

In [165]:
a3[:2,:2,:2]

array([[[ 1,  2],
        [ 4,  5]],

       [[10, 11],
        [13, 14]]])

In [166]:
a3[:2,:2,:2]

array([[[ 1,  2],
        [ 4,  5]],

       [[10, 11],
        [13, 14]]])

In [167]:
a4 = np.random.randint(10, size=(2,3,4,5))
a4

array([[[[6, 7, 7, 8, 1],
         [5, 9, 8, 9, 4],
         [3, 0, 3, 5, 0],
         [2, 3, 8, 1, 3]],

        [[3, 3, 7, 0, 1],
         [9, 9, 0, 4, 7],
         [3, 2, 7, 2, 0],
         [0, 4, 5, 5, 6]],

        [[8, 4, 1, 4, 9],
         [8, 1, 1, 7, 9],
         [9, 3, 6, 7, 2],
         [0, 3, 5, 9, 4]]],


       [[[4, 6, 4, 4, 3],
         [4, 4, 8, 4, 3],
         [7, 5, 5, 0, 1],
         [5, 9, 3, 0, 5]],

        [[0, 1, 2, 4, 2],
         [0, 3, 2, 0, 7],
         [5, 9, 0, 2, 7],
         [2, 9, 2, 3, 3]],

        [[2, 3, 4, 1, 2],
         [9, 1, 4, 6, 8],
         [2, 3, 0, 0, 6],
         [0, 6, 3, 3, 8]]]])

In [168]:
a4[:,:,:,:4]

array([[[[6, 7, 7, 8],
         [5, 9, 8, 9],
         [3, 0, 3, 5],
         [2, 3, 8, 1]],

        [[3, 3, 7, 0],
         [9, 9, 0, 4],
         [3, 2, 7, 2],
         [0, 4, 5, 5]],

        [[8, 4, 1, 4],
         [8, 1, 1, 7],
         [9, 3, 6, 7],
         [0, 3, 5, 9]]],


       [[[4, 6, 4, 4],
         [4, 4, 8, 4],
         [7, 5, 5, 0],
         [5, 9, 3, 0]],

        [[0, 1, 2, 4],
         [0, 3, 2, 0],
         [5, 9, 0, 2],
         [2, 9, 2, 3]],

        [[2, 3, 4, 1],
         [9, 1, 4, 6],
         [2, 3, 0, 0],
         [0, 6, 3, 3]]]])

## Manipulating Arrays & comparing arrays

Arithmetic

In [169]:
a1

array([1, 2, 3])

In [170]:
ones = np.ones(3)
ones

array([1., 1., 1.])

In [171]:
a1 + ones

array([2., 3., 4.])

In [172]:
a1 - ones

array([0., 1., 2.])

In [173]:
a1 * ones

array([1., 2., 3.])

In [174]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [175]:
a2 * a1

array([[ 1. ,  4. ,  9.9],
       [ 4. , 10. , 19.5]])

In [176]:
a2 * a3

ValueError: operands could not be broadcast together with shapes (2,3) (2,3,3) 

In [ ]:
np.random.seed(0)
sales_amouts = np.random.randint(20, size=(5,3))
sales_amouts

array([[12, 15,  0],
       [ 3,  3,  7],
       [ 9, 19, 18],
       [ 4,  6, 12],
       [ 1,  6,  7]])

In [184]:
weekly_sales = pd.DataFrame(sales_amouts, index=["Mon", "Tues", "Wed", "Thurs", "Fri"], columns=["Almond butter", "Peanut butter", "Cashew butter"])
weekly_sales

Almond butter  Peanut butter  Cashew butter
Mon               12             15              0
Tues               3              3              7
Wed                9             19             18
Thurs              4              6             12
Fri                1              6              7

In [ ]:
prices = np.array([10,8,12])
prices

array([10,  8, 12])

In [ ]:
butter_prices = pd.DataFrame(prices.reshape(1,3), index=["Price"], columns=["Almond butter", "Peanut butter", "Cashew butter"])
butter_prices

Almond butter  Peanut butter  Cashew butter
Price             10              8             12

In [177]:
total_sales = prices.dot(sales_amouts)

ValueError: shapes (3,) and (5,3) not aligned: 3 (dim 0) != 5 (dim 0)

In [178]:
prices.shape

(3,)

In [179]:
sales_amouts.shape

(5, 3)

In [180]:
total_sales = prices.dot(sales_amouts.T)
total_sales

array([240, 138, 458, 232, 142])

In [182]:
butter_prices

Almond butter  Peanut butter  Cashew butter
Price             10              8             12

In [185]:
weekly_sales

Almond butter  Peanut butter  Cashew butter
Mon               12             15              0
Tues               3              3              7
Wed                9             19             18
Thurs              4              6             12
Fri                1              6              7

In [187]:
butter_prices.shape, weekly_sales.shape

((1, 3), (5, 3))

In [189]:
daily_sales = butter_prices.dot(weekly_sales.T)
daily_sales

Mon  Tues  Wed  Thurs  Fri
Price  240   138  458    232  142

In [190]:
weekly_sales["Total ($)"] = daily_sales
weekly_sales

ValueError: Cannot set a DataFrame with multiple columns to the single column Total ($)

In [191]:
weekly_sales["Total ($)"] = daily_sales.T
weekly_sales

Almond butter  Peanut butter  Cashew butter  Total ($)
Mon               12             15              0        240
Tues               3              3              7        138
Wed                9             19             18        458
Thurs              4              6             12        232
Fri                1              6              7        142

## Comparison Operators

In [192]:
a1 > a2

array([[False, False, False],
       [False, False, False]])

In [193]:
a1 >= a2

array([[ True,  True, False],
       [False, False, False]])

In [196]:
# sorting arrays
random_array = np.random.randint(10, size=(3,5))
random_array

array([[4, 3, 6, 9, 8],
       [0, 8, 5, 9, 0],
       [9, 6, 5, 3, 1]])

In [197]:
np.sort(random_array)

array([[3, 4, 6, 8, 9],
       [0, 0, 5, 8, 9],
       [1, 3, 5, 6, 9]])

In [198]:
np.argsort(random_array)

array([[1, 0, 2, 4, 3],
       [0, 4, 2, 1, 3],
       [4, 3, 2, 1, 0]])

In [200]:
from matplotlib.image import imread

panda  = imread("./images/panda.png")
type(panda)

numpy.ndarray

In [201]:
panda

array([[[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       [[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       [[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       ...,

       [[0.13333334, 0.07450981, 0.05490196],
        [0.12156863, 0.0627451 , 0.04313726],
        [0.10980392, 0

In [202]:
panda.size, panda.shape, panda.ndim

(24465000, (2330, 3500, 3), 3)

In [203]:
car  = imread("./images/car-photo.png")
type(car)

numpy.ndarray

In [204]:
dog  = imread("./images/dog-photo.png")
type(dog)

numpy.ndarray

In [205]:
dog

array([[[0.70980394, 0.80784315, 0.88235295, 1.        ],
        [0.72156864, 0.8117647 , 0.8862745 , 1.        ],
        [0.7411765 , 0.8156863 , 0.8862745 , 1.        ],
        ...,
        [0.49803922, 0.6862745 , 0.8392157 , 1.        ],
        [0.49411765, 0.68235296, 0.8392157 , 1.        ],
        [0.49411765, 0.68235296, 0.8352941 , 1.        ]],

       [[0.69411767, 0.8039216 , 0.8862745 , 1.        ],
        [0.7019608 , 0.8039216 , 0.88235295, 1.        ],
        [0.7058824 , 0.80784315, 0.88235295, 1.        ],
        ...,
        [0.5019608 , 0.6862745 , 0.84705883, 1.        ],
        [0.49411765, 0.68235296, 0.84313726, 1.        ],
        [0.49411765, 0.68235296, 0.8392157 , 1.        ]],

       [[0.6901961 , 0.8       , 0.88235295, 1.        ],
        [0.69803923, 0.8039216 , 0.88235295, 1.        ],
        [0.7058824 , 0.80784315, 0.88235295, 1.        ],
        ...,
        [0.5019608 , 0.6862745 , 0.84705883, 1.        ],
        [0.49803922, 0.686274